---
# tasks file for db

- name: Load OS-specific vars
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"   # ex: debian.yml, ubuntu.yml
        - "{{ ansible_os_family }}.yml"      # ex: debian.yml, redhat.yml
        - "default"                              # fallback
      paths: "{{ role_path }}/vars"

- name: Starting MariaDB role
  ansible.builtin.debug:
    msg: "Hello from DB role"

- name: Install
  include_tasks: install.yml

- name: Configure
  include_tasks: configure.yml
