---

ansible_python_interpreter: /usr/bin/python3

nginx_main_conf: {}

nginx_confs:
  default.conf:
    listen: 80
    server_name: localhost
    root: /var/www/html
    index: index.html index.htm index.php

