---
- name: Configure webserver
  hosts: web
  gather_facts: True
  tasks:
    - name: Display container informations
      ansible.builtin.debug:
        msg:
        - "OS: {{ ansible_distribution }}"
        - "Hostname: {{ ansible_hostname }}"

    - name: Include web role
      ansible.builtin.include_role:
        name: web
      vars:
        nginx_confs: "{{ yaml_nginx_confs }}"

    - name: Enable our custom Nginx configuration
      ansible.builtin.file:
        src: /etc/nginx/conf.d/custom.conf
        dest: /etc/nginx/sites-enabled/custom.conf
        state: link
        force: yes

    - name: Reload Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
        enabled: yes
        use: service
