---
- name: Configure webserver
  hosts: web
  gather_facts: True
  tasks:
    - name: Display container informations
      ansible.builtin.debug:
        msg:
        - "OS: {{ ansible_distribution }}"
        - "Hostname: {{ ansible_hostname }}"

    - name: Include web role
      ansible.builtin.include_role:
        name: web
      vars:
        nginx_confs: "{{ yaml_nginx_confs }}"
