---
- name: Configure wordpress
  hosts: wordpress
  gather_facts: True
  tasks:
    - name: Display container informations
      ansible.builtin.debug:
        msg:
        - "OS: {{ ansible_distribution }}"
        - "Hostname: {{ ansible_hostname }}"

    - name: Include wordpress role
      ansible.builtin.include_role:
        name: wordpress
      vars:
        wp_website_url: "{{ website_url }}"
        wordpress_site_title: "{{ wp_site_title }}"
        #users
        wordpress_admin_user: "{{ wp_admin_user }}"
        wordpress_admin_password: "{{ wp_admin_password }}"
        wordpress_admin_email: "{{ wp_admin_email }}"
        wordpress_user_username: "{{ wp_user_username }}"
        wordpress_user_password: "{{ wp_user_password }}"
        wordpress_user_email: "{{ wp_user_email }}"
        #database
        wordpress_db_name: "{{ db_name }}"
        wordpress_db_user: "{{ db_user_username }}"
        wordpress_db_password: "{{ db_user_password }}"
        wordpress_db_host: "{{ db_host }}"
        wordpress_db_port: "{{ db_port }}"
        #others
        wordpress_path: "/var/www/html"