---
# Purpose: Prepare the instance before running the role under test.
# This is where you set up prerequisites like databases, web servers, etc.
- name: Prepare WP
  hosts: all
  gather_facts: false  # Must be false to install Python first
  vars_files:
    - vars/main.yml
    - vars/Debian.yml
  tasks:

    - name: Update apt cache
      raw: apt-get update
      changed_when: false

    - name: Install Python and base tools
      raw: >
        apt-get install -y
        python3 python3-apt python3-pip python3-pymysql
        ca-certificates curl
      changed_when: false

    - name: Gather facts now that Python is installed
      ansible.builtin.setup:
      
    - name: Install and configure MariaDB for WordPress
      ansible.builtin.include_role:
        name: db
      vars:
        # Map WordPress variables to DB role variables
        # This ensures the database is created with the same credentials WordPress will use
        mariadb_name: "{{ wordpress_db_name }}"
        mariadb_user_username: "{{ wordpress_db_user }}"
        mariadb_user_password: "{{ wordpress_db_password }}"
        mariadb_admin_password: "test_admin_pass"
        mariadb_bind_address: "0.0.0.0"
        mariadb_host: "{{ wordpress_db_host }}"
        
