---
- name: Copy nginx main conf if overwritten
  ansible.builtin.copy:
    dest: "{{ __nginx_main_conf_file }}"
    content: "{{ nginx_main_conf }}"
    owner: www-data
    group: www-data
    mode: '0644'
  when: nginx_main_conf is defined and nginx_main_conf | length > 0

- name: Disable default nginx site
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Apply all nginx confs
  ansible.builtin.template:
    src: "yaml_to_nginx.conf.j2"
    dest: "/etc/nginx/conf.d/{{ item.key }}"
    owner: www-data
    group: www-data
    mode: '0644'
  loop: "{{ nginx_confs | dict2items }}"
  vars:
    nginx_config: "{{ item.value }}"
  when: nginx_confs is defined and nginx_confs | length > 0

- name: Reload nginx to apply configuration changes
  ansible.builtin.debug:
    msg: "Reloading nginx to apply configuration changes"
  notify:
    - reload nginx
  
- meta: flush_handlers
