---
# tasks file for web

- name: Load OS-specific vars
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}.yml"   # ex: debian.yml, ubuntu.yml
        - "{{ ansible_os_family | lower }}.yml"      # ex: debian.yml, redhat.yml
        - "default"
      paths: "{{ role_path }}/vars"

- name: Starting Nginx role
  ansible.builtin.debug:
    msg: "Hello from Nginx role"

- name: Install nginx
  include_tasks: install.yml

- name: Configure nginx
  include_tasks: configure.yml
