---
- name: Say Hello
  ansible.builtin.debug:
    msg: "Hello from Web role"

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: true
    clean: true

- name: Ensure Nginx is started
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started
