---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache
      raw: apt-get update
      changed_when: false

    - name: Install Python and base tools
      raw: >
        apt-get install -y
        python3 python3-apt python3-pip
        ca-certificates curl
      changed_when: false
