---
# handlers file for web

- name: start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
    use: service

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
    use: service

- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
    use: service
    enabled: yes
